### ISSUE TITLE
Decreasing delay of a tap remap

### ISSUE THREAD

**Issue by fhill2** [zsugabubus/interception-k2k#9]
Thank you for this very useful software, I am using it with Sway for some of my key remaps and its working really nicely.

I have the basic 'caps2esc' behaviour in my config:

`{ .base_key = KEY_CAPSLOCK, .tap_key = KEY_ESC, .repeat_key = KEY_LEFTCTRL }`

This is working great, however I notice (using wev/xev) that when the .base_key is pressed, there is an added delay between the physical press of the .base_key (Caps) and the registered .base_key (Caps) downpress in xev.
This sometimes causes the unintended behaviour of the modifer key being sent AFTER the key I want to be modified.

This only happens when I press both keys (Caps + N for example) in quick succession. 

For example:
Caps n ....becomes.... n Caps 
or 
Caps LeftMouse ...becomes... LeftMouse Caps

So I have been retraining myself to wait a few milliseconds longer before hitting the next key :D 

Is there a way to reduce the delay between the physical keypress and the downpress being registered?

**Comment by zsugabubus** [comment]
Hi!

> there is an added delay between the physical press of the .base_key (Caps) and the registered .base_key (Caps) downpress in xev

To be honest this part of your issue report is a bit unclear. According to the rule above you should never see CapsLock being pressed down, but only an Esc or LeftCtrl. 

> Caps LeftMouse ...becomes... LeftMouse Caps

(Of course) There is no connection (synchronization) between pointer and keyboard events, so that's where `.hold_key` comes into play:

https://github.com/zsugabubus/interception-k2k/blob/259a549b1e215c47f0d243e9e5f484ce490b61e6/caps2esc/caps2esc/tap-rules.h.in#L1

Also not sure why you have trimmed down the last few fields. Does not that work?

**Comment by fhill2** [comment]
Apologies for the mistakes in my original post.
I wasn't expecting any connection between pointer and keyboard events so my original provided example doesn't make sense!
Also, I did leave out the full map fields. Thank you for correcting me.

Yes I meant seeing LeftCtrl being pressed down in xev/wev monitor.

I actually was using an old version that didn't include .hold_immediately (from an old fork) so missed this parameter while reading through the comments/instructions in k2k.c
After updating & testing, it works like a charm.

tap-rules are working as usual, with the addition of the first downpress of the .base_key being registered too.

Thank you again for this very valuable software. This is a very reliable solution to implementing key remaps in a Wayland environment.

**Comment by zsugabubus** [comment]
Happy to hear it serves well for you.
